### ISSUE TITLE
Deployment and Integration Testing

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#481]
### What's your issue about?
We need a strategy for deployment and testing to a non-private testnet (and eventually deployment to mainnet). We should also discuss what tools/partnerships would make this process as easy as possible for Viper developers.

### How can it be fixed?
My ideal process is a python-based tool for deployment of Viper contracts. I am currently working on something using Web3.py, there is also Populus (and maybe Truffle).

#### Cute Animal Picture
![Proud Lion](https://i.pinimg.com/originals/19/96/37/1996370ba66c4a637a1cfb5c080cc8fc.jpg)

**Comment by DavidKnott** [comment]
We've worked out all the details with Piper and @jacqueswww and will start integrating Viper and Populus this coming week.  
I'm also excited to try out what you're building!

**Comment by fubuloubu** [comment]
Awesome, I want in on that conversation! Lol

I like Populus, but I haven't been using it because I had a different idea for contract organization, and I wanted to store my contract deployment parameters in a YAML so they are globally accessible for testing. Additionally, the version of pyethereum it uses doesn't have the `ethereum.tester` module, and I prefer testing in Python versus testing in Solidity.

**Comment by fubuloubu** [comment]
I was doing stuff like this in my YAML:

```yaml
subfolder1:
    contract1a:
        compiler: solidity
        args:
            arg1: foo
            arg2: bar
    contract1b:
        compiler: solidity
        args:
            # Get address from contract at this key in YAML
            contract1a_address: subfolder1/contract1a
            list_arg: [1, 2, 3]
subfolder2:
    contract2a:
        compiler: viper
        # No args required to deploy
```
